name: Bug report
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the form below.
        A minimal reproducible example would be greatly appreciated.
  - type: input
    id: version
    attributes:
      label: rwc version
      description: "e.g. v0.0.4 (output of rwc --version)"
      placeholder: "v0.0.4"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the bug.
      placeholder: |
        1. Save the following code to `bug.rw`
        2. Run `rwc bug.rw`
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Paste any stack traces, IR dumps, or relevant logs if available.
      render: shell
