blank_issues_enabled: false
contact_links:
  - name: Questions and discussions
    url: https://github.com/ryuichi1208/rw/discussions
    about: For questions and idea discussions, please use Discussions
